# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EmptyWeighing.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmptyWeighing(object):
    def setupUi(self, EmptyWeighing):
        EmptyWeighing.setObjectName("EmptyWeighing")
        EmptyWeighing.resize(1024, 768)
        EmptyWeighing.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.backButton = QtWidgets.QPushButton(EmptyWeighing)
        self.backButton.setGeometry(QtCore.QRect(24, 520, 151, 111))
        self.backButton.setStyleSheet("border: 1px solid white;")
        self.backButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/BackArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(103, 105))
        self.backButton.setObjectName("backButton")
        self.nextButton = QtWidgets.QPushButton(EmptyWeighing)
        self.nextButton.setGeometry(QtCore.QRect(850, 510, 151, 111))
        self.nextButton.setStyleSheet("border: 1px solid white;")
        self.nextButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/NextArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.nextButton.setIcon(icon1)
        self.nextButton.setIconSize(QtCore.QSize(103, 105))
        self.nextButton.setObjectName("nextButton")
        self.msg_label = QtWidgets.QLabel(EmptyWeighing)
        self.msg_label.setGeometry(QtCore.QRect(10, 310, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.msg_label.setFont(font)
        self.msg_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msg_label.setAutoFillBackground(False)
        self.msg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label.setObjectName("msg_label")
        self.label = QtWidgets.QLabel(EmptyWeighing)
        self.label.setGeometry(QtCore.QRect(400, 140, 171, 131))
        self.label.setStyleSheet("align: center;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/information.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.logo = QtWidgets.QLabel(EmptyWeighing)
        self.logo.setGeometry(QtCore.QRect(720, 10, 281, 81))
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/Logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.msg_label_2 = QtWidgets.QLabel(EmptyWeighing)
        self.msg_label_2.setGeometry(QtCore.QRect(10, 400, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.msg_label_2.setFont(font)
        self.msg_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msg_label_2.setAutoFillBackground(False)
        self.msg_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label_2.setObjectName("msg_label_2")

        self.retranslateUi(EmptyWeighing)
        QtCore.QMetaObject.connectSlotsByName(EmptyWeighing)

    def retranslateUi(self, EmptyWeighing):
        _translate = QtCore.QCoreApplication.translate
        EmptyWeighing.setWindowTitle(_translate("EmptyWeighing", "Trimble"))
        self.msg_label.setText(_translate("EmptyWeighing", "Abc"))
        self.msg_label_2.setText(_translate("EmptyWeighing", "Weight"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EmptyWeighing = QtWidgets.QWidget()
    ui = Ui_EmptyWeighing()
    ui.setupUi(EmptyWeighing)
    EmptyWeighing.show()
    sys.exit(app.exec_())
