# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InvalidPickupNumber.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvalidPickupNumber(object):
    def setupUi(self, InvalidPickupNumber):
        InvalidPickupNumber.setObjectName("InvalidPickupNumber")
        InvalidPickupNumber.resize(1024, 768)
        InvalidPickupNumber.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.logo = QtWidgets.QLabel(InvalidPickupNumber)
        self.logo.setGeometry(QtCore.QRect(710, 30, 281, 81))
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/Logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(InvalidPickupNumber)
        self.label.setGeometry(QtCore.QRect(440, 180, 191, 151))
        self.label.setStyleSheet("align: center;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/information.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.msg_label = QtWidgets.QLabel(InvalidPickupNumber)
        self.msg_label.setGeometry(QtCore.QRect(46, 393, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.msg_label.setFont(font)
        self.msg_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msg_label.setAutoFillBackground(True)
        self.msg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label.setObjectName("msg_label")
        self.nextButton = QtWidgets.QPushButton(InvalidPickupNumber)
        self.nextButton.setGeometry(QtCore.QRect(840, 550, 151, 111))
        self.nextButton.setStyleSheet("border: 1px solid white;")
        self.nextButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.nextButton.setIcon(icon)
        self.nextButton.setIconSize(QtCore.QSize(103, 105))
        self.nextButton.setObjectName("nextButton")
        self.backButton = QtWidgets.QPushButton(InvalidPickupNumber)
        self.backButton.setGeometry(QtCore.QRect(60, 550, 151, 111))
        self.backButton.setStyleSheet("border: 1px solid white;")
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/BackArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backButton.setIcon(icon1)
        self.backButton.setIconSize(QtCore.QSize(103, 105))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(InvalidPickupNumber)
        QtCore.QMetaObject.connectSlotsByName(InvalidPickupNumber)

    def retranslateUi(self, InvalidPickupNumber):
        _translate = QtCore.QCoreApplication.translate
        InvalidPickupNumber.setWindowTitle(_translate("InvalidPickupNumber", "Trimble"))
        self.msg_label.setText(_translate("InvalidPickupNumber", "Error"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InvalidPickupNumber = QtWidgets.QWidget()
    ui = Ui_InvalidPickupNumber()
    ui.setupUi(InvalidPickupNumber)
    InvalidPickupNumber.show()
    sys.exit(app.exec_())
