# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScanPickupNumber.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScanPickupNumber(object):
    def setupUi(self, ScanPickupNumber):
        ScanPickupNumber.setObjectName("ScanPickupNumber")
        ScanPickupNumber.resize(1024, 768)
        font = QtGui.QFont()
        font.setPointSize(12)
        ScanPickupNumber.setFont(font)
        ScanPickupNumber.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.logo = QtWidgets.QLabel(ScanPickupNumber)
        self.logo.setGeometry(QtCore.QRect(720, 30, 281, 81))
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/Logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(ScanPickupNumber)
        self.label.setGeometry(QtCore.QRect(220, 230, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.pickupLineEdit = QtWidgets.QLineEdit(ScanPickupNumber)
        self.pickupLineEdit.setGeometry(QtCore.QRect(420, 230, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pickupLineEdit.setFont(font)
        self.pickupLineEdit.setTabletTracking(True)
        self.pickupLineEdit.setAutoFillBackground(False)
        self.pickupLineEdit.setStyleSheet("border: 1px solid black;")
        self.pickupLineEdit.setFrame(True)
        self.pickupLineEdit.setDragEnabled(False)
        self.pickupLineEdit.setReadOnly(False)
        self.pickupLineEdit.setObjectName("pickupLineEdit")
        self.nextButton = QtWidgets.QPushButton(ScanPickupNumber)
        self.nextButton.setGeometry(QtCore.QRect(840, 550, 151, 111))
        self.nextButton.setStyleSheet("border: 1px solid white;")
        self.nextButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/NextArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.nextButton.setIcon(icon)
        self.nextButton.setIconSize(QtCore.QSize(103, 105))
        self.nextButton.setObjectName("nextButton")
        self.backButton = QtWidgets.QPushButton(ScanPickupNumber)
        self.backButton.setGeometry(QtCore.QRect(30, 550, 151, 111))
        self.backButton.setStyleSheet("border: 1px solid white;")
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/BackArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backButton.setIcon(icon1)
        self.backButton.setIconSize(QtCore.QSize(103, 105))
        self.backButton.setObjectName("backButton")
        self.Button_1 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_1.setGeometry(QtCore.QRect(420, 330, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_1.setFont(font)
        self.Button_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_1.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_1.setAutoDefault(False)
        self.Button_1.setObjectName("Button_1")
        self.Button_2 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_2.setGeometry(QtCore.QRect(500, 330, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_2.setFont(font)
        self.Button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_2.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_2.setAutoDefault(False)
        self.Button_2.setObjectName("Button_2")
        self.Button_3 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_3.setGeometry(QtCore.QRect(580, 330, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_3.setFont(font)
        self.Button_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_3.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_3.setAutoDefault(False)
        self.Button_3.setObjectName("Button_3")
        self.Button_4 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_4.setGeometry(QtCore.QRect(420, 410, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_4.setFont(font)
        self.Button_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_4.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_4.setAutoDefault(False)
        self.Button_4.setObjectName("Button_4")
        self.Button_7 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_7.setGeometry(QtCore.QRect(420, 490, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_7.setFont(font)
        self.Button_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_7.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_7.setAutoDefault(False)
        self.Button_7.setObjectName("Button_7")
        self.Button_6 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_6.setGeometry(QtCore.QRect(580, 410, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_6.setFont(font)
        self.Button_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_6.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_6.setAutoDefault(False)
        self.Button_6.setObjectName("Button_6")
        self.Button_5 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_5.setGeometry(QtCore.QRect(500, 410, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_5.setFont(font)
        self.Button_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_5.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_5.setAutoDefault(False)
        self.Button_5.setObjectName("Button_5")
        self.Button_8 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_8.setGeometry(QtCore.QRect(500, 490, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_8.setFont(font)
        self.Button_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_8.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_8.setAutoDefault(False)
        self.Button_8.setObjectName("Button_8")
        self.Button_9 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_9.setGeometry(QtCore.QRect(580, 490, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_9.setFont(font)
        self.Button_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_9.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_9.setAutoDefault(False)
        self.Button_9.setObjectName("Button_9")
        self.Button_0 = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_0.setGeometry(QtCore.QRect(500, 570, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_0.setFont(font)
        self.Button_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_0.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_0.setAutoDefault(False)
        self.Button_0.setObjectName("Button_0")
        self.Button_back = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_back.setGeometry(QtCore.QRect(580, 570, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_back.setFont(font)
        self.Button_back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_back.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_back.setAutoDefault(False)
        self.Button_back.setObjectName("Button_back")
        self.Button_dot = QtWidgets.QPushButton(ScanPickupNumber)
        self.Button_dot.setGeometry(QtCore.QRect(420, 570, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_dot.setFont(font)
        self.Button_dot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_dot.setStyleSheet("border: 1px solid black;\n"
"color: white;\n"
"background-color: rgb(45, 45, 45);")
        self.Button_dot.setAutoDefault(False)
        self.Button_dot.setObjectName("Button_dot")

        self.retranslateUi(ScanPickupNumber)
        QtCore.QMetaObject.connectSlotsByName(ScanPickupNumber)

    def retranslateUi(self, ScanPickupNumber):
        _translate = QtCore.QCoreApplication.translate
        ScanPickupNumber.setWindowTitle(_translate("ScanPickupNumber", "Form"))
        self.label.setText(_translate("ScanPickupNumber", "Scan Pickup Number"))
        self.Button_1.setText(_translate("ScanPickupNumber", "1"))
        self.Button_2.setText(_translate("ScanPickupNumber", "2"))
        self.Button_3.setText(_translate("ScanPickupNumber", "3"))
        self.Button_4.setText(_translate("ScanPickupNumber", "4"))
        self.Button_7.setText(_translate("ScanPickupNumber", "7"))
        self.Button_6.setText(_translate("ScanPickupNumber", "6"))
        self.Button_5.setText(_translate("ScanPickupNumber", "5"))
        self.Button_8.setText(_translate("ScanPickupNumber", "8"))
        self.Button_9.setText(_translate("ScanPickupNumber", "9"))
        self.Button_0.setText(_translate("ScanPickupNumber", "0"))
        self.Button_back.setText(_translate("ScanPickupNumber", "<-"))
        self.Button_dot.setText(_translate("ScanPickupNumber", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScanPickupNumber = QtWidgets.QWidget()
    ui = Ui_ScanPickupNumber()
    ui.setupUi(ScanPickupNumber)
    ScanPickupNumber.show()
    sys.exit(app.exec_())
