# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Signature.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signature(object):
    def setupUi(self, Signature):
        Signature.setObjectName("Signature")
        Signature.resize(1024, 768)
        Signature.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.logo = QtWidgets.QLabel(Signature)
        self.logo.setGeometry(QtCore.QRect(730, 20, 281, 81))
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/Logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.nextButton_2 = QtWidgets.QPushButton(Signature)
        self.nextButton_2.setGeometry(QtCore.QRect(90, 550, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nextButton_2.setFont(font)
        self.nextButton_2.setStyleSheet("border: 4px solid darkblue;\n"
"color: darkblue;\n"
"border-radius: 25px;")
        self.nextButton_2.setIconSize(QtCore.QSize(103, 105))
        self.nextButton_2.setObjectName("nextButton_2")
        self.nextButton_3 = QtWidgets.QPushButton(Signature)
        self.nextButton_3.setGeometry(QtCore.QRect(860, 550, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nextButton_3.setFont(font)
        self.nextButton_3.setStyleSheet("border: 4px solid darkblue;\n"
"color: darkblue;\n"
"border-radius: 25px;")
        self.nextButton_3.setIconSize(QtCore.QSize(103, 105))
        self.nextButton_3.setObjectName("nextButton_3")
        self.label = QtWidgets.QLabel(Signature)
        self.label.setGeometry(QtCore.QRect(110, 110, 811, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Signature)
        self.line.setGeometry(QtCore.QRect(130, 180, 771, 20))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Signature)
        self.line_2.setGeometry(QtCore.QRect(120, 190, 21, 321))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Signature)
        self.line_3.setGeometry(QtCore.QRect(890, 190, 20, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("")
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Signature)
        self.line_4.setWindowModality(QtCore.Qt.NonModal)
        self.line_4.setEnabled(True)
        self.line_4.setGeometry(QtCore.QRect(130, 500, 771, 20))
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")

        self.retranslateUi(Signature)
        QtCore.QMetaObject.connectSlotsByName(Signature)

    def retranslateUi(self, Signature):
        _translate = QtCore.QCoreApplication.translate
        Signature.setWindowTitle(_translate("Signature", "Trimble"))
        self.nextButton_2.setText(_translate("Signature", "RESET"))
        self.nextButton_3.setText(_translate("Signature", "OK"))
        self.label.setText(_translate("Signature", "Signature Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Signature = QtWidgets.QWidget()
    ui = Ui_Signature()
    ui.setupUi(Signature)
    Signature.show()
    sys.exit(app.exec_())
